-- THIS IS WILL DELETE THE TABLE IF IT WAS EXISTS BEFORE
DROP TABLE IF EXISTS location; 
-- HERE IS THE TABLE FOR LOCATION INFO
CREATE TABLE IF NOT EXISTS location (
    id SERIAL PRIMARY KEY,
    search_query VARCHAR(255),
    formatted_query VARCHAR(255),
    latitude NUMERIC(20,14),
    longitude NUMERIC(20,14)
);